### Import the dependencies

In [1]:
import nltk
import string
import numpy as np
import pandas as pd

from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

from tensorflow.keras.layers import Dense, Dropout, Lambda
from tensorflow.keras.models import Sequential
from tensorflow.keras.losses import MeanSquaredError, CategoricalCrossentropy
from tensorflow.sparse import  SparseTensor, to_dense

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.preprocessing import StandardScaler,OneHotEncoder

import gc

### Run garbage collection to free up memory

In [2]:
gc.collect()

20

### Increase the size of the columns to be able to view more data

In [3]:
# Set display column width to 500

pd.set_option('display.max_colwidth', 500)

### Read the training, validation, and test data

In [4]:
# Read the csv files

data_train = pd.read_csv("train.txt", sep=';', header=None)
data_val = pd.read_csv("val.txt", sep=';', header=None)
data_test = pd.read_csv("test.txt", sep=';', header=None)

# Set the column headers of the dataframes

data_train.columns = ['text', 'label']
data_val.columns = ['text', 'label']
data_test.columns = ['text', 'label']

# Combine all three dataframes into one

data = pd.concat((data_train,data_val,data_test),axis=0)

data.head()

text  \
0                                                                                       i didnt feel humiliated   
1  i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake   
2                                                              im grabbing a minute to post i feel greedy wrong   
3                  i am ever feeling nostalgic about the fireplace i will know that it is still on the property   
4                                                                                          i am feeling grouchy   

     label  
0  sadness  
1  sadness  
2    anger  
3     love  
4    anger

### Remove punctuation

In [5]:
### Create a punct_count column to contain the number of punctuation characters in each line of data
data["punct_count"] = len([char for char in data["text"] if char in string.punctuation])

### Get the frequency of the number of punctuation counts 
data["punct_count"].value_counts()

0    20000
Name: punct_count, dtype: int64

### Tokenization

In [6]:
# nltk stopwords
from nltk.tokenize import word_tokenize

# Additional Stop words
data['text_tokenized'] = data["text"].apply(lambda x: word_tokenize(x))

In [7]:
data.head()

text  \
0                                                                                       i didnt feel humiliated   
1  i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake   
2                                                              im grabbing a minute to post i feel greedy wrong   
3                  i am ever feeling nostalgic about the fireplace i will know that it is still on the property   
4                                                                                          i am feeling grouchy   

     label  punct_count  \
0  sadness            0   
1  sadness            0   
2    anger            0   
3     love            0   
4    anger            0   

                                                                                                                       text_tokenized  
0                                                                                                        [i, didnt, feel, humiliated]  
1  [i, can, go, from, feeling, so, hopeless, to, so, damned, hopeful, just, from, being, around, someone, who, cares, and, is, awake]  
2                                                                         [im, grabbing, a, minute, to, post, i, feel, greedy, wrong]  
3                     [i, am, ever, feeling, nostalgic, about, the, fireplace, i, will, know, that, it, is, still, on, the, property]  
4                                                                                                           [i, am, feeling, grouchy]

In [8]:
data["label"].value_counts()

joy         6761
sadness     5797
anger       2709
fear        2373
love        1641
surprise     719
Name: label, dtype: int64

### Remove stopwords

In [9]:
# nltk stopwords
stopwords = nltk.corpus.stopwords.words('english')

# Additional Stop words
stop_words = ["arent", "cant", "couldnt", "didnt", "doesnt", "dont", "hadnt", "hasnt", "havent", "hed", "hell", "hes", "Id", "Ill", "Im", "Ive", "isnt", "lets", "mightnt", "mustnt", "shant", "shed", "shell", "shes", "shouldnt", "thats", "theres", "theyd", "theyll", "theyre", "theyve", "wed", "were", "weve", "werent", "whatll", "whatre", "whats", "whatve", "wheres", "whos", "wholl", "whore", "whos", "whove", "wont", "wouldnt", "youd", "youll", "youre", "youve"]

In [10]:
def remove_stopwords(word_list):
    return " ".join([WordNetLemmatizer().lemmatize(word) for word in word_list if word not in stopwords and word not in stop_words])

data["text_tokenized_nostop"] = data["text_tokenized"].apply(lambda x: remove_stopwords(x))
data.head()

text  \
0                                                                                       i didnt feel humiliated   
1  i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake   
2                                                              im grabbing a minute to post i feel greedy wrong   
3                  i am ever feeling nostalgic about the fireplace i will know that it is still on the property   
4                                                                                          i am feeling grouchy   

     label  punct_count  \
0  sadness            0   
1  sadness            0   
2    anger            0   
3     love            0   
4    anger            0   

                                                                                                                       text_tokenized  \
0                                                                                                        [i, didnt, feel, humiliated]   
1  [i, can, go, from, feeling, so, hopeless, to, so, damned, hopeful, just, from, being, around, someone, who, cares, and, is, awake]   
2                                                                         [im, grabbing, a, minute, to, post, i, feel, greedy, wrong]   
3                     [i, am, ever, feeling, nostalgic, about, the, fireplace, i, will, know, that, it, is, still, on, the, property]   
4                                                                                                           [i, am, feeling, grouchy]   

                                          text_tokenized_nostop  
0                                               feel humiliated  
1  go feeling hopeless damned hopeful around someone care awake  
2                     im grabbing minute post feel greedy wrong  
3          ever feeling nostalgic fireplace know still property  
4                                               feeling grouchy

### Vectorize

### Run garbage collection to free up memory

In [11]:
gc.collect()

20

In [12]:
count_vect = CountVectorizer()
X_count_vect = count_vect.fit_transform(data.iloc[:data.shape[0],:]["text_tokenized_nostop"])

X_features = pd.DataFrame(X_count_vect.toarray())
X_features.head()


0      1      2      3      4      5      6      7      8      9      ...  \
0      0      0      0      0      0      0      0      0      0      0  ...   
1      0      0      0      0      0      0      0      0      0      0  ...   
2      0      0      0      0      0      0      0      0      0      0  ...   
3      0      0      0      0      0      0      0      0      0      0  ...   
4      0      0      0      0      0      0      0      0      0      0  ...   

   15037  15038  15039  15040  15041  15042  15043  15044  15045  15046  
0      0      0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0      0      0  

[5 rows x 15047 columns]

### Convert the features dataframe, X_features, to a numpy array and store the result in X

In [13]:
X = X_features.to_numpy()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

### Encode the labels column into 6 one-hot-encoded columns, one column for each of the available labels

In [14]:
encoder = OneHotEncoder()
y = encoder.fit_transform(data[["label"]])
pd.DataFrame(y.toarray())

0    1    2    3    4    5
0      0.0  0.0  0.0  0.0  1.0  0.0
1      0.0  0.0  0.0  0.0  1.0  0.0
2      1.0  0.0  0.0  0.0  0.0  0.0
3      0.0  0.0  0.0  1.0  0.0  0.0
4      1.0  0.0  0.0  0.0  0.0  0.0
...    ...  ...  ...  ...  ...  ...
19995  1.0  0.0  0.0  0.0  0.0  0.0
19996  1.0  0.0  0.0  0.0  0.0  0.0
19997  0.0  0.0  1.0  0.0  0.0  0.0
19998  0.0  0.0  1.0  0.0  0.0  0.0
19999  0.0  1.0  0.0  0.0  0.0  0.0

[20000 rows x 6 columns]

### Convert sparse matrix to SparseTensor

In [15]:
def convert_sparse_matrix_to_sparse_tensor(X):
    coo = X.tocoo()
    indices = np.mat([coo.row, coo.col]).transpose()
    return SparseTensor(indices, coo.data, coo.shape)

### Retrieve the training, validation, and test datasets from the larger dataset

In [16]:
# Training
X_train = X[:data_train.shape[0],:]
y_train = y[:data_train.shape[0]]

# Validation
X_val = X[data_train.shape[0]:data_train.shape[0] + data_val.shape[0],:]
y_val = y[data_train.shape[0]:data_train.shape[0] + data_val.shape[0]]

# Test
X_test = X[data_train.shape[0] + data_val.shape[0]:data_train.shape[0]
              + data_val.shape[0] 
              + data_test.shape[0],:]
y_test = y[data_train.shape[0] + data_val.shape[0]:data_train.shape[0]
              + data_val.shape[0] 
              + data_test.shape[0]:]


### Convert target dataframes to dense tensors

In [17]:
y_train = to_dense(convert_sparse_matrix_to_sparse_tensor(y_train))
y_val = to_dense(convert_sparse_matrix_to_sparse_tensor(y_val))
y_test = to_dense(convert_sparse_matrix_to_sparse_tensor(y_test))

### Create the neural network

In [18]:
seq = Sequential()
seq.add(Dense(units=1000,activation="relu",input_dim=X_train.shape[1]))
seq.add(Dropout(0.2))
seq.add(Dense(units=50,activation="relu"))
seq.add(Dropout(0.2))
seq.add(Dense(units=6,activation="softmax"))

seq.compile(loss="categorical_crossentropy", optimizer="rmsprop", metrics=["accuracy"])

### Run garbage collection to free up memory

In [19]:
gc.collect()

20

### Fit the sequential model to the training, validating with the validation data

In [20]:
# Train the model

fit_model = seq.fit(X_train,y_train,epochs=20, validation_data=(X_val, y_val))

Epoch 1/20
500/500 [==============================] - 62s 125ms/step - loss: 0.6952 - accuracy: 0.7611 - val_loss: 0.3119 - val_accuracy: 0.8925
Epoch 2/20
500/500 [==============================] - 63s 125ms/step - loss: 0.2180 - accuracy: 0.9262 - val_loss: 0.2964 - val_accuracy: 0.8995
Epoch 3/20
500/500 [==============================] - 63s 127ms/step - loss: 0.1548 - accuracy: 0.9509 - val_loss: 0.3257 - val_accuracy: 0.9035
Epoch 4/20
500/500 [==============================] - 64s 127ms/step - loss: 0.1203 - accuracy: 0.9607 - val_loss: 0.3850 - val_accuracy: 0.9035
Epoch 5/20
500/500 [==============================] - 64s 127ms/step - loss: 0.0954 - accuracy: 0.9678 - val_loss: 0.4479 - val_accuracy: 0.9040
Epoch 6/20
500/500 [==============================] - 66s 131ms/step - loss: 0.0831 - accuracy: 0.9737 - val_loss: 0.4606 - val_accuracy: 0.9030
Epoch 7/20
500/500 [==============================] - 62s 123ms/step - loss: 0.0704 - accuracy: 0.9792 - val_loss: 0.4826 - val_ac

### Run garbage collection to free up memory

In [21]:
gc.collect()

1502

### Predict the labels of the test dataset

In [22]:
y_test_pred = seq.predict(X_test,use_multiprocessing=True)

### Retrieve the test portion of the larger dataframe 

In [23]:
y_test_nparray = y[data_train.shape[0] + data_val.shape[0]:data_train.shape[0]
              + data_val.shape[0] 
              + data_test.shape[0]:]

### Function to convert lists of floats into lists of ints

In [24]:
def float_to_int(fl):
    int_2d = []
    for row in fl:
        i_row = []
        for x in row:
            i_row.append(int(x+0.5))
        int_2d.append(i_row)
    
    return np.array(int_2d)
    

### Display the raw predictions

In [25]:
y_test_pred

array([[3.46451090e-10, 3.10430891e-12, 2.16507487e-08, 2.28953079e-10,
        1.00000000e+00, 1.79888283e-15],
       [7.41598069e-06, 1.78853938e-07, 1.22544825e-05, 4.23727755e-08,
        9.99980092e-01, 1.05738795e-09],
       [1.73220997e-12, 8.53572550e-15, 6.61328603e-10, 6.05693948e-15,
        1.00000000e+00, 1.12153552e-18],
       ...,
       [1.51227891e-12, 6.05553639e-13, 1.00000000e+00, 5.27890620e-08,
        2.29030038e-13, 4.66550237e-15],
       [3.00674552e-09, 6.46842538e-14, 9.99924064e-01, 7.58912211e-05,
        1.07362907e-09, 4.84394859e-12],
       [2.94989554e-11, 5.57748042e-02, 2.32384441e-08, 5.04289277e-09,
        3.70280624e-08, 9.44225192e-01]], dtype=float32)

### Convert the elements of the prediction dataframe to int

In [26]:
y_test_pred = float_to_int(y_test_pred)
y_test_pred

array([[0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       ...,
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1]])

### Determine the accuracy of the predicted results

In [28]:
(y_test_pred == y_test_nparray).sum()/(y_test_pred.shape[0] * y_test_pred.shape[1])

0.9654166666666667